#!/usr/bin/env bash
cd "$(dirname "$0")" || exit
echo "Bootstrap installs all dependencies."

echo "Installing features from git@github.com:casper-network/sdk-std-test-resources.git"

if [ -d "../cspr-standard-test-resources" ]
then
    echo "cspr-standard-test-resources exists fetching submodules."
    git submodule update --init --recursive
else
    echo "Cloning sdk-std-test-resources.git as submodule."
    git submodule add git@github.com:casper-network/sdk-std-test-resources.git ../sdk-std-test-resources
fi

if [ -d "../src/test/resources/features" ]
then
  echo "Features symbolic link already exists"
else
  echo "Creating features symbolic link required for IntelliJ debugging of features"
  ln -s $(realpath -s "../sdk-std-test-resources/features") ../src/test/resources/features
fi