#!/usr/bin/env bash
cd "$(dirname "$0")" || exit
echo "Bootstrap installs all dependencies."

if [ -d "../src/test/resources/features" ]
then
  echo "Features symbolic link already exists"
else
  echo "Creating features symbolic link required for IntelliJ debugging of features"
  ln -s $(realpath -s "../cspr-standard-tests-resources/features") ../src/test/resources/features
fi


echo "Installing features from git@github.com:stormeye2000/cspr-standard-tests-resources.git"

if [ -d "../cspr-standard-test-resources" ]
then
    echo "Create symbolic link for IntelliJ to allow debug of features"
    cd ../src/tresest/resources
     ln -s ../casper-java-sdk/cspr-standard-tests-resources/features features

    echo "cspr-standard-test-resources exists fetching submodules."

    git submodule update --init --recursive

else
    echo "Cloning cspr-standard-test-resources as submodule."
    git submodule add git@github.com:stormeye2000/cspr-standard-tests-resources.git ../cspr-standard-tests-resources
fi
