#!/usr/bin/env bash
BASEDIR=$(builtin cd .. || exit 1; pwd)
#CONTAINER_NAME="cspr-nctl"
CONTAINER_NAME="cspr-nctl-condor"
# clear the assets folder
rm -rf  "${BASEDIR}/assets"
mkdir "${BASEDIR}/assets"
# copy net-1 users
docker cp ${CONTAINER_NAME}:/home/casper/casper-nctl/assets/net-1/users "${BASEDIR}/assets/net-1"
# copy net-1 chainspec
docker cp ${CONTAINER_NAME}:/home/casper/casper-nctl/assets/net-1/chainspec "${BASEDIR}/assets/net-1"
# copy faucet keys
docker cp ${CONTAINER_NAME}:/home/casper/casper-nctl/assets/net-1/faucet "${BASEDIR}/assets/net-1"
