#!/usr/bin/env bash
# remote debugs one or more cucumber e2e tests, the 1st parameter is the cucumber name regex eg:
# ./script/e2e-remote-debug info_get_peers
# The above example will start the JVM in debug mode and only execute the info_get_peers scenario.
# The above example will start the JVM in debug mode and only execute the info_get_peers scenario.

cd "$(dirname "$0")/.."|| exit 1
./gradlew --stop
./gradlew cucumber -Dorg.gradle.jvmargs='-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005;' -Dcucumber.name="${1}" --no-daemon