#!/usr/bin/env bash
cd "$(dirname "$0")" || exit
cd ..
echo "Removes all test resources git submodules."
git submodule deinit -f cspr-standard-tests-resources
rm -rf .git/modules/cspr-standard-tests-resources
git rm -f cspr-standard-tests-resources
rm .gitmodules
