# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [maven-migration]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
#        uses: actions/setup-java@v1
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # see https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md
          java-version: 8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: PGP_PASSPHRASE
#          server-username: OSSRH_USERNAME
#          server-password: OSSRH_PASSWORD
#          gpg-passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
#          gpg --list-secret-keys --keyid-format LONG
#      - name: Clean settings.xml
#        run: rm -rf ~/.m2/settings.xml
#
#      - name: Create settings.xml
#        uses: s4u/maven-settings-action@v2.4.1
#        with:
#          servers: '[{"id": "ossrh", "username": "${{secrets.OSSRH_USERNAME}}", "password": "${{secrets.OSSRH_PASSWORD}}", "passphrase": "${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}"}]'

      - id: publish-to-central
        name: Publish to Central Repository
        env:
          MAVEN_USERNAME: "${{ secrets.OSSRH_USERNAME }}"
          MAVEN_PASSWORD: "${{ secrets.OSSRH_PASSWORD }}"
          PGP_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Darguments=-Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            clean deploy
#          clean deploy -e -X
