# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [maven-migration]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: ossrh
#          server-username: OSSRH_USERNAME
#          server-password: OSSRH_PASSWORD
          username: OSSRH_USERNAME
          password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_SECRET_KEY_PASSWORD
      - name: Build with Maven
        run: mvn -B compile --file pom.xml

      - name: Test with Maven
        run: mvn -B test --file pom.xml

      - name: Publish to Apache Maven Central
        run: mvn -DskipTests deploy -Dgpg.passphrase=${{ secrets.MAVEN_GPG_SECRET_KEY_PASSWORD }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_SECRET_KEY_PASSWORD }}